# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call('_smogllim_timesTwo', PACKAGE = 'smogllim', x)
}

mat_transpose <- function(m) {
    .Call('_smogllim_mat_transpose', PACKAGE = 'smogllim', m)
}

cpp_logsumexp <- function(x, axis = 1L) {
    .Call('_smogllim_cpp_logsumexp', PACKAGE = 'smogllim', x, axis)
}

cpp_loggausspdf <- function(X, mu, Sigma) {
    .Call('_smogllim_cpp_loggausspdf', PACKAGE = 'smogllim', X, mu, Sigma)
}

